development:
  adapter: mysql
  database: ritzylunch_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: ritzylunch_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: ritzylunch_production
  username: root
  password: clarksburgritzy
  host: localhost
  pool: 5
  timeout: 5000