development:
  adapter: mysql
  database: ritzylunch_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: ritzylunch_test
  username: root
  password:
  host: localhost