development: # ritzylunch.local
  api_key: ABQIAAAAu7h2qzhjNgZHWvY17SwGDRSX78-u-9Lw1ZXjId7Kdzejnrgc5xQjGqpp0XKjUS33Y2ny6r2caaBirA
production: # ritzylunchwv.com
  api_key: ABQIAAAAu7h2qzhjNgZHWvY17SwGDRS-2gFxHVtZid6joR1f-CN6rFnS2xQyiE1Qnx3tRUHvf83WoHVVo6hPTw